// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetapp.Models;

#nullable disable

namespace dotnetapp.Migrations
{
    [DbContext(typeof(FootballdbContext))]
    partial class FootballdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dotnetapp.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Appearances")
                        .HasColumnType("int")
                        .HasColumnName("appearances");

                    b.Property<int?>("Goals")
                        .HasColumnType("int")
                        .HasColumnName("goals");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int?>("Positionid")
                        .HasColumnType("int")
                        .HasColumnName("positionid");

                    b.Property<int?>("Shirtno")
                        .HasColumnType("int")
                        .HasColumnName("shirtno");

                    b.HasKey("Id")
                        .HasName("PK__players__3213E83F9F9D2EBD");

                    b.HasIndex("Positionid");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("dotnetapp.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__position__3213E83F9863F2D3");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("dotnetapp.Models.Player", b =>
                {
                    b.HasOne("dotnetapp.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("Positionid");

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
